### ISSUE TITLE
Couldn't create connection to server.

### ISSUE THREAD

**Issue by Fexxix** [gleam-lang/vscode-gleam#57] opened 2024-03-11 18:47 UTC
This is all the detail it provided in the output.
![image](https://github.com/gleam-lang/vscode-gleam/assets/121352884/ff11e501-75ca-4aac-80fd-6b51a334da6d)

I have installed gleam and all the necessary dependencies by following the docs and verified the installation too. If you need further detail then just ask.

**Comment by lpil** [comment] 2024-03-11 21:19
Hello! The error ENOENT means that the `gleam` executable could not be found at the given path, which indicates there's something awry with your installation. Does running Gleam work in other contexts?

**Comment by Fexxix** [comment] 2024-03-12 00:53
> Hello! The error ENOENT means that the `gleam` executable could not be found at the given path, which indicates there's something awry with your installation. Does running Gleam work in other contexts?

doing `which gleam` logs the following:
`~/.cargo/bin/gleam`
and yes, it does work in other contexts.

If I copy the binary to `/usr/local/bin/`, the output then changes to:
```
Hello human!

This command is intended to be run by language server clients such
as a text editor rather than being run directly in the console.

Many editors will automatically start the language server for you
when you open a Gleam project. If yours does not you may need to
look up how to configure your editor to use a language server.

You can exit this program by pressing ctrl+c.
```

**Comment by Fexxix** [comment] 2024-03-12 01:12
> This is all the detail it provided in the output. ![image](https://private-user-images.githubusercontent.com/121352884/311830741-ff11e501-75ca-4aac-80fd-6b51a334da6d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAyMDU4NTgsIm5iZiI6MTcxMDIwNTU1OCwicGF0aCI6Ii8xMjEzNTI4ODQvMzExODMwNzQxLWZmMTFlNTAxLTc1Y2EtNGFhYy04MGZkLTZiNTFhMzM0ZGE2ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxMlQwMTA1NThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iNjFhMDcxNTY4ODBlYTgyYmQwMGQ2OTUwMzg4M2Q4MzU4NDg0YjU4ODkwOTdlYjdmYWZhN2ExMDFmYjZmOGQyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.8Zu8I4Yb1bUXtHX8RL7QmIamvcGc1rlukq9P2_dlcEY)
> 
> I have installed gleam and all the necessary dependencies by following the docs and verified the installation too. If you need further detail then just ask.

> Hello! The error ENOENT means that the `gleam` executable could not be found at the given path, which indicates there's something awry with your installation. Does running Gleam work in other contexts?



Hmmm... I copied the binary to `/usr/local/bin` again and this time it worked with the following logs:
```
 INFO language_server_starting
Hello human!

This command is intended to be run by language server clients such
as a text editor rather than being run directly in the console.

Many editors will automatically start the language server for you
when you open a Gleam project. If yours does not you may need to
look up how to configure your editor to use a language server.

You can exit this program by pressing ctrl+c.

 INFO creating_new_language_server_engine path="/home/fexxix/Coding/gleem"
 INFO removing_build_state_from_different_gleam_version
 INFO compile{package=gleam_stdlib}: analysing_modules count=21
 INFO compile{package=gleeunit}: analysing_modules count=2
 INFO compile{package=gleem}: analysing_modules count=2
 INFO compile{package=gleam_stdlib}: analysing_modules count=17
 INFO compile{package=gleeunit}: analysing_modules count=2
 INFO compile{package=gleem}: analysing_modules count=2
 INFO compile{package=gleam_stdlib}: analysing_modules count=17
 INFO compile{package=gleeunit}: analysing_modules count=2
 INFO compile{package=gleem}: analysing_modules count=2
 INFO compile{package=gleam_stdlib}: analysing_modules count=17
 INFO compile{package=gleeunit}: analysing_modules count=2
 INFO compile{package=gleam_stdlib}: analysing_modules count=17
 INFO compile{package=gleeunit}: analysing_modules count=2
 INFO compile{package=gleem}: analysing_modules count=2
 INFO compile{package=gleam_stdlib}: analysing_modules count=17
 INFO compile{package=gleeunit}: analysing_modules count=2
 INFO compile{package=gleem}: analysing_modules count=2
 INFO compile{package=gleam_stdlib}: analysing_modules count=17
 INFO compile{package=gleeunit}: analysing_modules count=2
 INFO compile{package=gleem}: analysing_modules count=2
 INFO compile{package=gleam_stdlib}: analysing_modules count=17
 INFO compile{package=gleeunit}: analysing_modules count=2
 INFO compile{package=gleem}: analysing_modules count=2
 INFO compile{package=gleam_stdlib}: analysing_modules count=17
 INFO compile{package=gleeunit}: analysing_modules count=2
 INFO compile{package=gleem}: analysing_modules count=2
 INFO compile{package=gleam_stdlib}: analysing_modules count=17
 INFO compile{package=gleeunit}: analysing_modules count=2
 INFO compile{package=gleam_stdlib}: analysing_modules count=17
 INFO compile{package=gleeunit}: analysing_modules count=2
 INFO compile{package=gleem}: analysing_modules count=2
```

It's working right now but I'd like to keep the issue open since I don't know if this is the right fix.

**Comment by lpil** [comment] 2024-03-12 11:38
Fab! This means your editor was unable to run the Gleam binary, likely due to the PATH being different in your editor to not include the cargo bin directory. I'll close this issue as the problem isn't related to the plugin. Thank you

**Closed by lpil** 2024-03-12 11:38 UTC

**Comment by Fexxix** [comment] 2024-03-12 12:47
> Fab! This means your editor was unable to run the Gleam binary, likely due to the PATH being different in your editor to not include the cargo bin directory. I'll close this issue as the problem isn't related to the plugin. Thank you

I see, thanks anyway. And since I have the chance, thank you for creating gleam. I pretty much fell in love at 1st sight.
